spring:
  application:
    name: chat-sample
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      javax:
        persistence:
          validation:
            mode: none
      show-sql: true
security:
  jwt:
    token:
      secret-key: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
      expire-length: 1800000 # 30분
logging:
  level:
    xyz.mon0mon.chatsample: debug
