### GET employees list
GET http://localhost:8080/employees

### Get single employee
GET http://localhost:8080/employees/1

### EmployeeNotFoundException
GET http://localhost:8080/employees/100

### Register new employee
POST http://localhost:8080/employees
Content-Type: application/json

{
  "name": "spring test",
  "role": "framework"
}

### Edit employee
PUT http://localhost:8080/employees/1
Content-Type: application/json

{
  "name": "tom jack",
  "role": "manager"
}

### Delete employee
DELETE http://localhost:8080/employees/2


### Get orders list
GET http://localhost:8080/orders

### Get order
GET http://localhost:8080/orders/1

### Register order
POST http://localhost:8080/orders
Content-Type: application/json

{
  "description": "Something"
}

### Cancel order
DELETE http://localhost:8080/orders/2/cancel

### Method not allowed
DELETE http://localhost:8080/orders/1/cancel

### Complete order
PUT http://localhost:8080/orders/2/complete

### Method not allowed
PUT http://localhost:8080/orders/1/complete
